//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUser
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CertNo { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
        public string Password { get; set; }
        public string AvatorImg { get; set; }
        public System.DateTime AddTime { get; set; }
        public bool IsDelete { get; set; }
    }
}
